'use client';

import useSWR from 'swr';
import { useTimezone } from '@/lib/timezone';
import { formatDateInTimezone } from '@/lib/date-utils';

interface SignalHistoryProps {
  symbol: string;
  refreshKey: number;
  refreshInterval?: number;
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function SignalHistory({ symbol, refreshKey, refreshInterval = 0 }: SignalHistoryProps) {
  const { timezone } = useTimezone();
  const { data, error } = useSWR(
    `/api/strategy/analyze?symbol=${symbol}&limit=20&refresh=${refreshKey}`,
    fetcher,
    {
      refreshInterval: refreshInterval,
    }
  );

  if (error) {
    return (
      <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-gray-200/50 p-8">
        <h2 className="text-2xl font-bold mb-6 text-gray-900 flex items-center gap-2">
          📊 <span>Signal History</span>
        </h2>
        <p className="text-red-500 font-semibold text-base">Error loading signals</p>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-gray-200/50 p-8">
        <h2 className="text-2xl font-bold mb-6 text-gray-900 flex items-center gap-2">
          📊 <span>Signal History</span>
        </h2>
        <p className="text-gray-500 text-base">Loading signals...</p>
      </div>
    );
  }

  const signals = data.signals || [];

  return (
    <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-gray-200/50 p-8">
      <h2 className="text-2xl font-bold mb-6 text-gray-900 flex items-center gap-2">
        📊 <span>Signal History</span>
      </h2>
      <div className="space-y-3 max-h-96 overflow-y-auto pr-2 custom-scrollbar">
        {signals.length === 0 ? (
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border-2 border-blue-200 rounded-xl p-6">
            <p className="text-gray-700 font-semibold text-base mb-2">
              📊 No signals yet for {symbol}
            </p>
            <p className="text-gray-600 text-sm mb-4">
              To generate a signal for this symbol, click the <strong>&quot;🔍 Analyze Strategy&quot;</strong> button in the Strategy Control section above.
            </p>
            <p className="text-gray-500 text-xs">
              Signals are generated by analyzing technical indicators (RSI & MACD) and saved to the database. 
              Auto-trading via GitHub Actions only generates signals for symbols configured in TRADING_SYMBOLS secret.
            </p>
          </div>
        ) : (
          signals.map((signal: {
            _id: string;
            timestamp: string | Date;
            symbol: string;
            signal: 'BUY' | 'SELL' | 'HOLD';
            closePrice?: number;
            rsi?: number;
            macd?: number;
            macdSignal?: number;
            macdHistogram?: number;
            executed?: boolean;
            orderId?: string;
          }) => (
            <div
              key={signal._id}
              className="border-2 border-gray-200 rounded-xl p-4 hover:bg-gradient-to-r hover:from-blue-50 hover:to-indigo-50 transition-all hover:border-blue-300"
            >
              <div className="flex justify-between items-start mb-3">
                <div className="flex items-center gap-2">
                  <span
                    className={`inline-block px-3 py-1.5 rounded-lg text-sm font-black uppercase ${
                      signal.signal === 'BUY'
                        ? 'bg-green-500 text-white'
                        : signal.signal === 'SELL'
                        ? 'bg-red-500 text-white'
                        : 'bg-gray-500 text-white'
                    }`}
                  >
                    {signal.signal}
                  </span>
                  {signal.executed === true && (
                    <span className="text-xs text-green-600 font-bold bg-green-50 px-2 py-1 rounded">
                      ✓ Executed
                    </span>
                  )}
                </div>
                <span className="text-sm text-gray-600 font-medium">
                  {formatDateInTimezone(signal.timestamp, timezone, 'MMM dd, HH:mm')}
                </span>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <span className="text-gray-600 font-medium text-sm">Price</span>
                  <span className="font-bold text-base text-gray-900">
                    ${(signal.closePrice ?? 0).toFixed(2)}
                  </span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="flex justify-between">
                    <span className="text-gray-600 text-sm">RSI</span>
                    <span className={`font-medium text-sm ${
                      (signal.rsi ?? 0) < 30 ? 'text-green-600' : 
                      (signal.rsi ?? 0) > 70 ? 'text-red-600' : 
                      'text-gray-700'
                    }`}>
                      {(signal.rsi ?? 0).toFixed(2)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600 text-sm">MACD</span>
                    <span className={`font-medium text-sm ${
                      (signal.macd ?? 0) > (signal.macdSignal ?? 0) ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {(signal.macd ?? 0).toFixed(4)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600 text-sm">Signal</span>
                    <span className="font-medium text-sm text-gray-700">
                      {(signal.macdSignal ?? 0).toFixed(4)}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600 text-sm">Histogram</span>
                    <span className={`font-medium text-sm ${
                      (signal.macdHistogram ?? 0) > 0 ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {(signal.macdHistogram ?? 0).toFixed(4)}
                    </span>
                  </div>
                </div>
                {signal.orderId && (
                  <div className="flex justify-between items-center pt-2 border-t border-gray-200">
                    <span className="text-gray-600 font-medium text-xs">Order ID</span>
                    <span className="font-mono text-xs text-gray-500 truncate max-w-[200px]">{signal.orderId}</span>
                  </div>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
